apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: franasync2
  description: fran async api2
spec:
  type: asyncapi
  lifecycle: production
  owner: devxteam1
  system: baas
  definition: |
    asyncapi: 2.6.0
    info:
      title: Hello world application
      version: '0.1.0'
    channels:
      hello:
        publish:
          message:
            payload:
              type: string
              pattern: '^hello .+$'
