apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-corp
  description: The acme-corp organization
  links:
    - url: http://www.acme.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: ACME Corp
    email: info@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [infrastructure]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  description: The infra department
spec:
  type: department
  # Intentional no profile for testing
  parent: acme-corp
  children: [backstage, boxoffice]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
  description: The backstage sub-department
spec:
  type: sub-department
  profile:
    displayName: Backstage
    email: backstage@example.com
    picture: https://avatars.dicebear.com/api/identicon/backstage@example.com.svg?background=%23fff&margin=25
  parent: infrastructure
  children: [devxteam1, devxteam2]
